AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.0.2
  Exclude:
    - 'tmp/**/*'

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/MixinGrouping:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/LineLength:
  Max: 126

Metrics/ClassLength:
  Max: 100

Metrics/ModuleLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 23

Metrics/PerceivedComplexity:
  Max: 30

Metrics/ParameterLists:
  Max: 6

Layout/DotPosition:
  EnforcedStyle: trailing

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '{}'

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 40

Metrics/AbcSize:
  Max: 83

Metrics/BlockLength:
  Max: 100

Style/GlobalVars:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/FormatStringToken:
  Enabled: false

Style/Encoding:
  Enabled: true

Naming/MethodParameterName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/AndOr:
  Enabled: false

Security/Open:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Lint/CircularArgumentReference:
  Enabled: true

Style/DateTime:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Style/SlicingWithRange:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: false

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true

Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true

Lint/DuplicateBranch: # (new in 1.3)
  Enabled: false

Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true

Lint/EmptyBlock: # (new in 1.1)
  Enabled: false

Lint/EmptyClass: # (new in 1.3)
  Enabled: true

Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: false

Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true

Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true

Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true

Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true

Style/CollectionCompact: # (new in 1.2)
  Enabled: true

Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true

Style/HashExcept: # (new in 1.7)
  Enabled: true

Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true

Style/NilLambda: # (new in 1.3)
  Enabled: true

Style/RedundantArgument: # (new in 1.4)
  Enabled: true

Style/SwapValues: # (new in 1.1)
  Enabled: true

Naming/VariableNumber:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false
